/***************************************************************************//**
  @file     gpio.c
  @brief    Simple GPIO Pin services driver implementation for Kinetis MCU
 ******************************************************************************/

/*******************************************************************************
 * INCLUDE HEADER FILES
 ******************************************************************************/

#include "gpio.h"
#include "hardware.h"


/*******************************************************************************
 * STATIC VARIABLES AND CONST VARIABLES WITH FILE LEVEL SCOPE
 ******************************************************************************/

/** Base pointers array for GPIO peripheral instances (GPIOA, GPIOB, etc.) */
static GPIO_Type * const gpios[] = GPIO_BASE_PTRS;

/** Base pointers array for PORT control peripheral instances (PORTA, PORTB, etc.) */
static PORT_Type * const ports[] = PORT_BASE_PTRS;

/** NVIC Interrupt Vector numbers for each Port module */
static uint32_t portsIRQn[] = {
    PORTA_IRQn, PORTB_IRQn, PORTC_IRQn, PORTD_IRQn, PORTE_IRQn
};

/** Registered callback function pointers array indexed by Port [0..4] and Pin [0..31] */
static pinIrqFun_t portHandler[5][32];

/** Counter of active interrupt handlers registered per port */
static int porIrqCounters[5];

/** List of active pin numbers configured with IRQ per port */
static int activeHandlers[5][32];

/*******************************************************************************
 * GLOBAL FUNCTION DEFINITIONS
 ******************************************************************************/

/**
 * @brief Configures pin mode (INPUT, OUTPUT, PULLUP, PULLDOWN).
 * @param pin Composite pin identifier generated by PORTNUM2PIN.
 * @param mode Target pin mode (INPUT, OUTPUT, INPUT_PULLUP, INPUT_PULLDOWN).
 */
void gpioMode (pin_t pin, uint8_t mode)
{
    GPIO_Type * gpio = gpios[PIN2PORT(pin)];
    PORT_Type * port = ports[PIN2PORT(pin)];

    /* Configure pin MUX selection to ALT1 (GPIO functionality) */
    port->PCR[PIN2NUM(pin)] &= ~(7 << PORT_PCR_MUX_SHIFT);
    port->PCR[PIN2NUM(pin)] |= (1 << PORT_PCR_MUX_SHIFT);
    port->PCR[PIN2NUM(pin)] &= ~PORT_PCR_PE_MASK;

    /* Set data direction register and internal pull resistors configuration */
    if(mode == OUTPUT)
    {
        gpio->PDDR |= (uint32_t)((uint32_t)1 << PIN2NUM(pin));
    } else if (mode == INPUT){
        gpio->PDDR &= ~((uint32_t)1 << PIN2NUM(pin));
    } else{
        /* Enable pull resistor (PE) and select Pull Up / Pull Down (PS) */
        port->PCR[PIN2NUM(pin)] |= PORT_PCR_PE_MASK |
                ((uint32_t)((uint8_t)INPUT_PULLDOWN - mode)
                << PORT_PCR_PS_SHIFT);
    }
}

/**
 * @brief Configures pin interrupt detection mode and attaches callback routine.
 * @param pin Composite pin identifier generated by PORTNUM2PIN.
 * @param irqMode Trigger condition (Rising edge, Falling edge, Both edges, Disabled).
 * @param irqFun Callback function to execute upon interrupt detection.
 * @return True if callback registration succeeded, false otherwise.
 */
bool gpioIRQ(pin_t pin, uint8_t irqMode, pinIrqFun_t irqFun)
{

    if(irqFun == (pinIrqFun_t)0)
        return 0;

    if(irqMode > 3)
        return 0;

    PORT_Type * port = ports[PIN2PORT(pin)];

    /* Clear existing IRQ configuration */
    port->PCR[PIN2NUM(pin)] &= ~(15U << PORT_PCR_IRQC_SHIFT);

    /* Clear pending Interrupt Status Flag (ISF) */
    port->ISFR = (1U << PIN2NUM(pin));

    /* Configure requested IRQ trigger condition */
    port->PCR[PIN2NUM(pin)] |= (irqMode ? irqMode + 8U : 0) << PORT_PCR_IRQC_SHIFT;

    /* Store handler reference in active registration table */
    portHandler[PIN2PORT(pin)][PIN2NUM(pin)] = irqFun;
    activeHandlers[PIN2PORT(pin)][porIrqCounters[PIN2PORT(pin)]++] = PIN2NUM(pin);

    /* Enable NVIC line for target Port */
    NVIC_EnableIRQ(portsIRQn[PIN2PORT(pin)]);

    return 1;
}

/**
 * @brief Sets output level of a digital pin HIGH or LOW.
 * @param pin Composite pin identifier generated by PORTNUM2PIN.
 * @param value Desired pin state (HIGH or LOW).
 */
void gpioWrite(pin_t pin, bool value)
{
    GPIO_Type * gpio = gpios[PIN2PORT(pin)];

    if(value){
        gpio->PSOR = ((uint32_t)1 << PIN2NUM(pin)); /* Set Output Register */
    } else
        gpio->PCOR = ((uint32_t)1 << PIN2NUM(pin)); /* Clear Output Register */
}

/**
 * @brief Toggles output state of a digital pin.
 * @param pin Composite pin identifier generated by PORTNUM2PIN.
 */
void gpioToggle(pin_t pin)
{
    GPIO_Type * gpio = gpios[PIN2PORT(pin)];

    gpio->PTOR = ((uint32_t)1 << PIN2NUM(pin)); /* Toggle Output Register */
}

/**
 * @brief Reads current digital state of a pin.
 * @param pin Composite pin identifier generated by PORTNUM2PIN.
 * @return True if state is HIGH, false if state is LOW.
 */
bool gpioRead(pin_t pin)
{
    GPIO_Type * gpio = gpios[PIN2PORT(pin)];

    return ((uint32_t)1 << PIN2NUM(pin)) ==
            (gpio->PDIR & ((uint32_t)1 << PIN2NUM(pin)));
}

/**
 * @brief Enables and configures pin digital glitch filter.
 * @param pin Composite pin identifier generated by PORTNUM2PIN.
 * @param clk Filter clock source selection flag.
 * @param count Filter clock count duration limit (0 to 31).
 * @return True if filter parameters were valid and configured, false otherwise.
 */
bool gpioDigitalFilter(pin_t pin, bool clk, uint32_t count)
{
    if(count > 31)
    {
        return 0;
    }

    PORT_Type * port = ports[PIN2PORT(pin)];

    port->DFWR &= ~(31 << 0U);
    port->DFWR |= (count << 0U);

    port->DFER |= (1 << PIN2NUM(pin));

    if(clk)
    {
        port->DFCR &= (1 << 0U);
    } else
    {
        port->DFCR |= (1 << 0U);
    }

    return 1;
}

/*******************************************************************************
 * INTERRUPT SERVICE ROUTINES & LOCAL FUNCTIONS
 ******************************************************************************/

/**
 * @brief Generic dispatcher handling Port pin interrupts.
 * @param portNum Index corresponding to target Port (PA - PE).
 */
static void gpioPortIRQHandler(uint8_t portNum)
{
    for(int i = 0; i < porIrqCounters[portNum]; i++)
    {
        /* Check if Interrupt Status Flag (ISF) is set for active registered pin */
        if((ports[portNum]->ISFR & (1U << activeHandlers[portNum][i])) != 0U)
        {
            /* Clear flag by writing 1 to ISFR bit */
            ports[portNum]->ISFR = 1U << activeHandlers[portNum][i];
            
            /* Execute registered pin callback */
            portHandler[portNum][activeHandlers[portNum][i]]();
        }
    }
}

/** @brief Port A hardware interrupt service routine. */
void PORTA_IRQHandler(void)
{
    gpioPortIRQHandler(PA);
}

/** @brief Port B hardware interrupt service routine. */
void PORTB_IRQHandler(void)
{
    gpioPortIRQHandler(PB);
}

/** @brief Port C hardware interrupt service routine. */
void PORTC_IRQHandler(void)
{
    gpioPortIRQHandler(PC);
}

/** @brief Port D hardware interrupt service routine. */
void PORTD_IRQHandler(void)
{
    gpioPortIRQHandler(PD);
}

/** @brief Port E hardware interrupt service routine. */
void PORTE_IRQHandler(void)
{
    gpioPortIRQHandler(PE);
}
